name: docs
on: [push, pull_request]


jobs:
  build-docs:
    name: Build and generate docs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Build docs
      run: |
        sudo apt-get install pandoc
        pip install --upgrade -r requirements_docs.txt
        pip install --upgrade .[all]
        mkdir docs_build
        sphinx-build -nW -b html docs docs_build