name: pytest_and_coveralls
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt
        pip install -r requirements_test.txt
        pip install matplotlib
        pip install -e .
    - name: Test with coverage
      run: |
        coverage run --source symfit -m py.test
    - name: Upload to Coveralls
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          coveralls --service=github